---
kind: ConfigMap
apiVersion: v1
metadata:
  name: datashop-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
  labels:
    app: datashop
data:
  LOG_LEVEL: {{ .Values.logging.application_log_level }}
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: 'true'
  RAILS_SERVE_STATIC_FILES: 'true'
  WEB_CONCURRENCY: '1'
  CLOUD_PROVIDER: AWS
  PORT: '8080'
  DISABLE_CREDIT_CARDS: 'true'
