apiVersion: v1
kind: Service
metadata:
  name: datashop-nodeport-service
spec:
  selector:
    app: datashop
    tier: frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: {{ .Values.service.port }}
