apiVersion: apps/v1
kind: Deployment
metadata:
  name: datashop-web
  labels:
    app: datashop
    tier: frontend
spec:
  selector:
    matchLabels:
      app: datashop
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: datashop
        tier: frontend
    spec:
      containers:
      - name: datashop-web
        image: {{ .Values.images.webapp }}
        volumeMounts:
          - name: datashop-secrets
            mountPath: "/etc/syndetic"
            readOnly: true
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        readinessProbe:
          httpGet:
              path: /api/healthy
              port: 8080
          initialDelaySeconds: 10
        env:
        - name: GET_HOSTS_FROM
          value: dns
        envFrom:
        - configMapRef:
            name: datashop-config
        ports:
        - containerPort: 8080
      volumes:
        - name: datashop-secrets
          secret:
            secretName: datashop-web
