apiVersion: batch/v1
kind: Job
metadata:
  name: dsmigrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: dsmigrate
          image: {{ .Values.images.webapp }}
          volumeMounts:
            - name: datashop-secrets
              mountPath: "/etc/syndetic"
              readOnly: true
          command: ['rails']
          args: ['db:migrate']
          env:
          - name: GET_HOSTS_FROM
            value: dns
          envFrom:
          - configMapRef:
              name: datashop-config
      volumes:
        - name: datashop-secrets
          secret:
            secretName: datashop-web
