apiVersion: v1
kind: Secret
metadata:
  name: datashop-web
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  aws-bucket-name: {{ .Values.secrets.aws_s3_bucket | b64enc | quote }}
  aws-access-key-id: {{ .Values.secrets.aws_access_key | b64enc | quote }}
  aws-secret-access-key: {{ .Values.secrets.aws_secret_access_key | b64enc | quote }}
  database-url: {{ .Values.secrets.database_url | b64enc | quote }}
  cloudfront-host: {{ .Values.secrets.cloudfront_host | b64enc | quote }}
  secret-key-base: {{ .Values.secrets.secret_key_base | b64enc | quote }}
  smtp-address: {{ .Values.email.smtp_address | b64enc | quote }}
  smtp-username: {{ .Values.email.smtp_username | b64enc | quote }}
  smtp-password: {{ .Values.email.smtp_password | b64enc | quote }}
  smtp-domain: {{ .Values.email.smtp_domain | b64enc | quote }}
  smtp-port: {{ .Values.email.smtp_port | b64enc | quote }}
  smtp-authentication: {{ .Values.email.smtp_authentication | b64enc | quote }}
  from-address: {{ .Values.email.from_address | b64enc | quote }}
  {{- if .Values.okta.okta_client_id }}
  okta-client-id: {{ .Values.okta.okta_client_id | b64enc | quote }}
  okta-client-secret: {{ .Values.okta.okta_client_secret | b64enc | quote }}
  okta-site: {{ .Values.okta.okta_site | b64enc | quote }}
  {{- end }}
  {{- if .Values.keycloak.keycloak_client_id }}
  keycloak-client-id: {{ .Values.keycloak.keycloak_client_id | b64enc | quote }}
  keycloak-client-secret: {{ .Values.keycloak.keycloak_client_secret | b64enc | quote }}
  keycloak-site: {{ .Values.keycloak.keycloak_site | b64enc | quote }}
  keycloak-realm: {{ .Values.keycloak.keycloak_realm | b64enc | quote }}
  {{- end }}
