apiVersion: v1
kind: Secret
metadata:
  name: datashop-web
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  aws-bucket-name: {{ .Values.secrets.aws_s3_bucket | b64enc | quote }}
  aws-access-key-id: {{ .Values.secrets.aws_access_key | b64enc | quote }}
  aws-secret-access-key: {{ .Values.secrets.aws_secret_access_key | b64enc | quote }}
  database-url: {{ .Values.secrets.database_url | b64enc | quote }}
  cloudfront-host: {{ .Values.secrets.cloudfront_host | b64enc | quote }}
  mailgun-api-key: {{ .Values.secrets.mailgun_api_key | b64enc | quote }}
  secret-key-base: {{ .Values.secrets.secret_key_base | b64enc | quote }}
