apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datashop-daily-subscriptions
spec:
  schedule: "30 10 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: datashop-daily-subscriptions
              image: {{ .Values.images.webapp }}
              volumeMounts:
                - name: datashop-secrets
                  mountPath: "/etc/syndetic"
                  readOnly: true
              command: ['bundle', 'exec', 'rails', 'subscriptions:daily_downloads']
              env:
              - name: GET_HOSTS_FROM
                value: dns
              envFrom:
              - configMapRef:
                  name: datashop-config
              ports:
              - containerPort: 8080
          volumes:
            - name: datashop-secrets
              secret:
                secretName: datashop-web
