apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: datashop-web-worker
  labels:
    app: datashop
    tier: worker-pool
spec:
  selector:
    matchLabels:
      app: datashop
      tier: worker-pool
  replicas: 3
  template:
    metadata:
      labels:
        app: datashop
        tier: worker-pool
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yml") . | sha256sum }}
    spec:
      containers:
      - name: datashop-web-worker
        image: {{ .Values.images.webapp }}
        volumeMounts:
          - name: datashop-secrets
            mountPath: "/etc/syndetic"
            readOnly: true
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        command:
          - bundle
          - exec
          - rails
          - jobs:work
        env:
        - name: GET_HOSTS_FROM
          value: dns
        envFrom:
        - configMapRef:
            name: datashop-config
        ports:
        - containerPort: 8080
      volumes:
        - name: datashop-secrets
          secret:
            secretName: datashop-web
